"""Ultrasonic Table

Revision ID: 309523495b30
Revises: 37f53d1d8f45
Create Date: 2022-10-10 21:07:10.710369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309523495b30'
down_revision = '37f53d1d8f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ultrasonic_data',
    sa.Column('distance', sa.String(length=10), nullable=True),
    sa.Column('date_time', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('date_time')
    )
    op.create_index(op.f('ix_ultrasonic_data_date_time'), 'ultrasonic_data', ['date_time'], unique=False)
    op.create_index(op.f('ix_ultrasonic_data_distance'), 'ultrasonic_data', ['distance'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ultrasonic_data_distance'), table_name='ultrasonic_data')
    op.drop_index(op.f('ix_ultrasonic_data_date_time'), table_name='ultrasonic_data')
    op.drop_table('ultrasonic_data')
    # ### end Alembic commands ###
