"""dhttable

Revision ID: 37f53d1d8f45
Revises: 
Create Date: 2022-10-10 20:56:51.681864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37f53d1d8f45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dht_data',
    sa.Column('humidity', sa.String(length=10), nullable=True),
    sa.Column('temperature', sa.String(length=10), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('date_time')
    )
    op.create_index(op.f('ix_dht_data_date_time'), 'dht_data', ['date_time'], unique=False)
    op.create_index(op.f('ix_dht_data_humidity'), 'dht_data', ['humidity'], unique=False)
    op.create_index(op.f('ix_dht_data_temperature'), 'dht_data', ['temperature'], unique=False)
    op.drop_table('dhtdata')
    op.drop_table('ultrasonicdata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ultrasonicdata',
    sa.Column('distance', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('date_time', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True)
    )
    op.create_table('dhtdata',
    sa.Column('humidity', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('date_time', sa.VARCHAR(length=30), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_dht_data_temperature'), table_name='dht_data')
    op.drop_index(op.f('ix_dht_data_humidity'), table_name='dht_data')
    op.drop_index(op.f('ix_dht_data_date_time'), table_name='dht_data')
    op.drop_table('dht_data')
    # ### end Alembic commands ###
