"""Added heat index to DHT table

Revision ID: 46408325111d
Revises: 309523495b30
Create Date: 2022-10-10 23:57:35.375694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46408325111d'
down_revision = '309523495b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dht_data', sa.Column('heat_index', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_dht_data_heat_index'), 'dht_data', ['heat_index'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dht_data_heat_index'), table_name='dht_data')
    op.drop_column('dht_data', 'heat_index')
    # ### end Alembic commands ###
